//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FadedVanguardLogUploader.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FadedVanguardLogUploader.Resources.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LNG_Close {
            get {
                return ResourceManager.GetString("LNG_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EVTC Files.
        /// </summary>
        public static string LNG_File_Count {
            get {
                return ResourceManager.GetString("LNG_File_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string LNG_Filter_From_SemiColon {
            get {
                return ResourceManager.GetString("LNG_Filter_From_SemiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar.
        /// </summary>
        public static string LNG_List_Bar_Tooltip {
            get {
                return ResourceManager.GetString("LNG_List_Bar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string LNG_List_Upload {
            get {
                return ResourceManager.GetString("LNG_List_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads selected files.
        /// </summary>
        public static string LNG_List_Upload_Tooltip {
            get {
                return ResourceManager.GetString("LNG_List_Upload_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinal Sabir.
        /// </summary>
        public static string LNG_Menu_Encounter_Adina {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Adina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetherblade Hideout.
        /// </summary>
        public static string LNG_Menu_Encounter_AetherbladeHideout {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_AetherbladeHideout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkk.
        /// </summary>
        public static string LNG_Menu_Encounter_Arkk {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Arkk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artsariiv.
        /// </summary>
        public static string LNG_Menu_Encounter_Artsariiv {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Artsariiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Camp.
        /// </summary>
        public static string LNG_Menu_Encounter_BanditTrio {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_BanditTrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boneskinner.
        /// </summary>
        public static string LNG_Menu_Encounter_Boneskinner {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Boneskinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken King.
        /// </summary>
        public static string LNG_Menu_Encounter_BrokenKing {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_BrokenKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cairn the Indomitable.
        /// </summary>
        public static string LNG_Menu_Encounter_Cairn {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Cairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold War.
        /// </summary>
        public static string LNG_Menu_Encounter_ColdWar {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_ColdWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjured Amalgamate.
        /// </summary>
        public static string LNG_Menu_Encounter_ConjuredAmalgamate {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_ConjuredAmalgamate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deimos.
        /// </summary>
        public static string LNG_Menu_Encounter_Deimos {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Deimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuum.
        /// </summary>
        public static string LNG_Menu_Encounter_Dhuum {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Dhuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eater of Souls.
        /// </summary>
        public static string LNG_Menu_Encounter_EaterOfSouls {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_EaterOfSouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensolyss of the Endless Torment.
        /// </summary>
        public static string LNG_Menu_Encounter_Ensolyss {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Ensolyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Dragons.
        /// </summary>
        public static string LNG_Menu_Encounter_EOD {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_EOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siege the Stronghold.
        /// </summary>
        public static string LNG_Menu_Encounter_Escort {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye of Judgment &amp; Eye of Fate.
        /// </summary>
        public static string LNG_Menu_Encounter_Eyes {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Eyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forging Steel.
        /// </summary>
        public static string LNG_Menu_Encounter_ForgingSteel {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_ForgingSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraenir of Jormag.
        /// </summary>
        public static string LNG_Menu_Encounter_FraenirOfJormag {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_FraenirOfJormag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Lair of the Snowmen.
        /// </summary>
        public static string LNG_Menu_Encounter_Freezie {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Freezie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorseval the Multifarious.
        /// </summary>
        public static string LNG_Menu_Encounter_Gorseval {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Gorseval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Temple.
        /// </summary>
        public static string LNG_Menu_Encounter_HarvestTemple {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_HarvestTemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaineng Overlook.
        /// </summary>
        public static string LNG_Menu_Encounter_KainengOverlook {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_KainengOverlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Construct.
        /// </summary>
        public static string LNG_Menu_Encounter_KeepConstruct {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_KeepConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Icebrood Saga.
        /// </summary>
        public static string LNG_Menu_Encounter_LW5 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_LW5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAMA.
        /// </summary>
        public static string LNG_Menu_Encounter_MAMA {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_MAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthias Gabrel.
        /// </summary>
        public static string LNG_Menu_Encounter_Mattias {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Mattias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mursaat Overseer.
        /// </summary>
        public static string LNG_Menu_Encounter_MursaatOverseer {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_MursaatOverseer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare Fractal.
        /// </summary>
        public static string LNG_Menu_Encounter_Nightmare {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qadim.
        /// </summary>
        public static string LNG_Menu_Encounter_Qadim {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Qadim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qadim the Peerless.
        /// </summary>
        public static string LNG_Menu_Encounter_QadimThePeerless {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_QadimThePeerless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River of Souls.
        /// </summary>
        public static string LNG_Menu_Encounter_RiverOfSouls {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_RiverOfSouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabetha the Saboteur.
        /// </summary>
        public static string LNG_Menu_Encounter_Sabetha {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Sabetha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinal Adina.
        /// </summary>
        public static string LNG_Menu_Encounter_Sabir {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Sabir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samarog.
        /// </summary>
        public static string LNG_Menu_Encounter_Samarog {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Samarog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shattered Observatory Fractal.
        /// </summary>
        public static string LNG_Menu_Encounter_ShatteredObservatory {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_ShatteredObservatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiverpeaks Pass.
        /// </summary>
        public static string LNG_Menu_Encounter_ShiverpeaksPass {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_ShiverpeaksPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siax the Corrupted.
        /// </summary>
        public static string LNG_Menu_Encounter_Siax {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Siax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skorvald the Shattered.
        /// </summary>
        public static string LNG_Menu_Encounter_Skorvald {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Skorvald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slothasor.
        /// </summary>
        public static string LNG_Menu_Encounter_Slothasor {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Slothasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulless Horror.
        /// </summary>
        public static string LNG_Menu_Encounter_SoullessHorror {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_SoullessHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunqua Peak Fractal.
        /// </summary>
        public static string LNG_Menu_Encounter_SunquaPeak {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_SunquaPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twin Largos.
        /// </summary>
        public static string LNG_Menu_Encounter_TwinLargos {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_TwinLargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twisted Castle.
        /// </summary>
        public static string LNG_Menu_Encounter_TwistedCastle {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_TwistedCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vale Guardian.
        /// </summary>
        public static string LNG_Menu_Encounter_ValeGuardian {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_ValeGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice of the Fallen and Claw of the Fallen.
        /// </summary>
        public static string LNG_Menu_Encounter_VoiceAndClawOfTheFallen {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_VoiceAndClawOfTheFallen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Vale.
        /// </summary>
        public static string LNG_Menu_Encounter_W1 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvation Pass.
        /// </summary>
        public static string LNG_Menu_Encounter_W2 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stronghold of the Faithful.
        /// </summary>
        public static string LNG_Menu_Encounter_W3 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bastion of the Penitent.
        /// </summary>
        public static string LNG_Menu_Encounter_W4 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Chains.
        /// </summary>
        public static string LNG_Menu_Encounter_W5 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythwright Gambit.
        /// </summary>
        public static string LNG_Menu_Encounter_W6 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key of Ahdashim.
        /// </summary>
        public static string LNG_Menu_Encounter_W7 {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_W7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper of Jormag.
        /// </summary>
        public static string LNG_Menu_Encounter_WhisperOfJormag {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_WhisperOfJormag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xera.
        /// </summary>
        public static string LNG_Menu_Encounter_Xera {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_Xera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xunlai Jade Junkyard.
        /// </summary>
        public static string LNG_Menu_Encounter_XunlaiJadeJunkyard {
            get {
                return ResourceManager.GetString("LNG_Menu_Encounter_XunlaiJadeJunkyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string LNG_Menu_File {
            get {
                return ResourceManager.GetString("LNG_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string LNG_Menu_File_Exit {
            get {
                return ResourceManager.GetString("LNG_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string LNG_Menu_File_SaveSettings {
            get {
                return ResourceManager.GetString("LNG_Menu_File_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string LNG_Menu_File_SelectFolder {
            get {
                return ResourceManager.GetString("LNG_Menu_File_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Data.
        /// </summary>
        public static string LNG_Menu_File_WipeData {
            get {
                return ResourceManager.GetString("LNG_Menu_File_WipeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filter.
        /// </summary>
        public static string LNG_Menu_Filter {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractels.
        /// </summary>
        public static string LNG_Menu_Filter_Fractels {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Fractels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids.
        /// </summary>
        public static string LNG_Menu_Filter_Raids {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Raids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort.
        /// </summary>
        public static string LNG_Menu_Filter_Sort {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Ascending.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Asc {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charcter Name.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_CharName {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_CharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Date {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Descending.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Des {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Length {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Username {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikes.
        /// </summary>
        public static string LNG_Menu_Filter_Strikes {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string LNG_Menu_Help {
            get {
                return ResourceManager.GetString("LNG_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LNG_Menu_Help_About {
            get {
                return ResourceManager.GetString("LNG_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string LNG_Menu_Settings {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string LNG_Menu_Settings_DarkMode {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW2 Api.
        /// </summary>
        public static string LNG_Menu_Settings_GW2Api {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_GW2Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Encounters Hidden.
        /// </summary>
        public static string LNG_Menu_Settings_HideErrors {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_HideErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LNG_Menu_Settings_Lang {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Amount.
        /// </summary>
        public static string LNG_Menu_Settings_PageAmount {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_PageAmount", resourceCulture);
            }
        }
    }
}
