//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FadedVanguardLogUploader.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FadedVanguardLogUploader.Resources.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LNG_Close {
            get {
                return ResourceManager.GetString("LNG_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EVTC Files.
        /// </summary>
        public static string LNG_File_Count {
            get {
                return ResourceManager.GetString("LNG_File_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string LNG_Filter_From_SemiColon {
            get {
                return ResourceManager.GetString("LNG_Filter_From_SemiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar.
        /// </summary>
        public static string LNG_List_Bar_Tooltip {
            get {
                return ResourceManager.GetString("LNG_List_Bar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string LNG_List_Upload {
            get {
                return ResourceManager.GetString("LNG_List_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads selected files.
        /// </summary>
        public static string LNG_List_Upload_Tooltip {
            get {
                return ResourceManager.GetString("LNG_List_Upload_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string LNG_Menu_File {
            get {
                return ResourceManager.GetString("LNG_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string LNG_Menu_File_Exit {
            get {
                return ResourceManager.GetString("LNG_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string LNG_Menu_File_SaveSettings {
            get {
                return ResourceManager.GetString("LNG_Menu_File_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string LNG_Menu_File_SelectFolder {
            get {
                return ResourceManager.GetString("LNG_Menu_File_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Data.
        /// </summary>
        public static string LNG_Menu_File_WipeData {
            get {
                return ResourceManager.GetString("LNG_Menu_File_WipeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filter.
        /// </summary>
        public static string LNG_Menu_Filter {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort.
        /// </summary>
        public static string LNG_Menu_Filter_Sort {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Ascending.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Asc {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charcter Name.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_CharName {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_CharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Date {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Descending.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Des {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Length {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LNG_Menu_Filter_Sort_Username {
            get {
                return ResourceManager.GetString("LNG_Menu_Filter_Sort_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string LNG_Menu_Help {
            get {
                return ResourceManager.GetString("LNG_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LNG_Menu_Help_About {
            get {
                return ResourceManager.GetString("LNG_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string LNG_Menu_Settings {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string LNG_Menu_Settings_DarkMode {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW2 Api.
        /// </summary>
        public static string LNG_Menu_Settings_GW2Api {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_GW2Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Encounters Hidden.
        /// </summary>
        public static string LNG_Menu_Settings_HideErrors {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_HideErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LNG_Menu_Settings_Lang {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Amount.
        /// </summary>
        public static string LNG_Menu_Settings_PageAmount {
            get {
                return ResourceManager.GetString("LNG_Menu_Settings_PageAmount", resourceCulture);
            }
        }
    }
}
